# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stringdb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stringdb.proto',
  package='stringdb',
  syntax='proto2',
  serialized_pb=_b('\n\x0estringdb.proto\x12\x08stringdb\"\x9a\x03\n\x07Request\x12+\n\x04type\x18\x01 \x02(\x0e\x32\x1d.stringdb.Request.RequestType\x12<\n\x11request_get_value\x18\x15 \x01(\x0b\x32!.stringdb.Request.RequestGetValue\x12<\n\x11request_set_value\x18\x16 \x01(\x0b\x32!.stringdb.Request.RequestSetValue\x12\x42\n\x14request_count_values\x18\x17 \x01(\x0b\x32$.stringdb.Request.RequestCountValues\x1a\x1e\n\x0fRequestGetValue\x12\x0b\n\x03key\x18\x01 \x02(\t\x1a-\n\x0fRequestSetValue\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x1a\x14\n\x12RequestCountValues\"=\n\x0bRequestType\x12\r\n\tGET_VALUE\x10\x01\x12\r\n\tSET_VALUE\x10\x02\x12\x10\n\x0c\x43OUNT_VALUES\x10\x03\"\x19\n\x08Response\x12\r\n\x05value\x18\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='stringdb.Request.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET_VALUE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_VALUE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COUNT_VALUES', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=378,
  serialized_end=439,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_REQUESTTYPE)


_REQUEST_REQUESTGETVALUE = _descriptor.Descriptor(
  name='RequestGetValue',
  full_name='stringdb.Request.RequestGetValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='stringdb.Request.RequestGetValue.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=307,
)

_REQUEST_REQUESTSETVALUE = _descriptor.Descriptor(
  name='RequestSetValue',
  full_name='stringdb.Request.RequestSetValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='stringdb.Request.RequestSetValue.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='stringdb.Request.RequestSetValue.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=354,
)

_REQUEST_REQUESTCOUNTVALUES = _descriptor.Descriptor(
  name='RequestCountValues',
  full_name='stringdb.Request.RequestCountValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=376,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='stringdb.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='stringdb.Request.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_get_value', full_name='stringdb.Request.request_get_value', index=1,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_set_value', full_name='stringdb.Request.request_set_value', index=2,
      number=22, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_count_values', full_name='stringdb.Request.request_count_values', index=3,
      number=23, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_REQUESTGETVALUE, _REQUEST_REQUESTSETVALUE, _REQUEST_REQUESTCOUNTVALUES, ],
  enum_types=[
    _REQUEST_REQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=439,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='stringdb.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='stringdb.Response.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=466,
)

_REQUEST_REQUESTGETVALUE.containing_type = _REQUEST
_REQUEST_REQUESTSETVALUE.containing_type = _REQUEST
_REQUEST_REQUESTCOUNTVALUES.containing_type = _REQUEST
_REQUEST.fields_by_name['type'].enum_type = _REQUEST_REQUESTTYPE
_REQUEST.fields_by_name['request_get_value'].message_type = _REQUEST_REQUESTGETVALUE
_REQUEST.fields_by_name['request_set_value'].message_type = _REQUEST_REQUESTSETVALUE
_REQUEST.fields_by_name['request_count_values'].message_type = _REQUEST_REQUESTCOUNTVALUES
_REQUEST_REQUESTTYPE.containing_type = _REQUEST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(

  RequestGetValue = _reflection.GeneratedProtocolMessageType('RequestGetValue', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST_REQUESTGETVALUE,
    __module__ = 'stringdb_pb2'
    # @@protoc_insertion_point(class_scope:stringdb.Request.RequestGetValue)
    ))
  ,

  RequestSetValue = _reflection.GeneratedProtocolMessageType('RequestSetValue', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST_REQUESTSETVALUE,
    __module__ = 'stringdb_pb2'
    # @@protoc_insertion_point(class_scope:stringdb.Request.RequestSetValue)
    ))
  ,

  RequestCountValues = _reflection.GeneratedProtocolMessageType('RequestCountValues', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST_REQUESTCOUNTVALUES,
    __module__ = 'stringdb_pb2'
    # @@protoc_insertion_point(class_scope:stringdb.Request.RequestCountValues)
    ))
  ,
  DESCRIPTOR = _REQUEST,
  __module__ = 'stringdb_pb2'
  # @@protoc_insertion_point(class_scope:stringdb.Request)
  ))
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.RequestGetValue)
_sym_db.RegisterMessage(Request.RequestSetValue)
_sym_db.RegisterMessage(Request.RequestCountValues)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'stringdb_pb2'
  # @@protoc_insertion_point(class_scope:stringdb.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
